### ISSUE TITLE
Add max width to the input on the form

### ISSUE THREAD

**Issue by thewholesihle** [TheWholePaycheck/DZUVHA-SOLAR-website#2]
The form inputs are too wide, a max width would be great.
![image](https://github.com/TheWholePaycheck/DZUVHA-SOLAR-website/assets/45470217/ea4b0ae6-5281-415b-bd33-cb8d5575557e)

**Comment by SimonRammala** [comment]
Reduced the width of the input size from 100% to 50% and add a display:flex; to the contact us section
![Screenshot (44)](https://github.com/TheWholePaycheck/DZUVHA-SOLAR-website/assets/101131942/7bc5388d-411a-4679-9bc9-2fa5bb6d1cb8)
